# 3. 神经网络

## 3.3 多维数组的运算

In [1]:
import numpy as np

In [2]:
X = np.array([1, 2])
print(X.shape)
W = np.array([[1, 3, 5], [2, 4, 6]])
print(W.shape)
print(W)
Y = np.dot(X, W)
print(Y)

(2,)
(2, 3)
[[1 3 5]
 [2 4 6]]
[ 5 11 17]
