In [1]:
import torch

In [2]:
torch.cuda.is_available()

False

In [3]:
x = torch.rand(3, 5)

In [4]:
print(x)

tensor([[0.4772, 0.0842, 0.0018, 0.3905, 0.1748],
        [0.3371, 0.4817, 0.3183, 0.5578, 0.9676],
        [0.6912, 0.5099, 0.4231, 0.1721, 0.6817]])


## Numpy

In [6]:
import numpy as np

In [8]:
arr_2_d = np.asarray([[1, 2], [3, 4]])
print(arr_2_d)

[[1 2]
 [3 4]]


In [9]:
arr_2_d.ndim

2

In [10]:
arr_2_d.shape

(2, 2)

In [11]:
arr_2_d.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [12]:
arr_2_d

array([[1, 2],
       [3, 4]])